### ISSUE TITLE
 No module named dqn

### ISSUE THREAD

**Issue by glazari** [osh/kerlym#5]
I downloaded the latest version of kerlym just now and when runing any example I get this:

`Traceback (most recent call last):
  File "/usr/local/bin/kerlym", line 5, in <module>
    pkg_resources.run_script('KeRLym==0.0.1', 'kerlym')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/KeRLym-0.0.1-py2.7.egg/EGG-INFO/scripts/kerlym", line 6, in <module>

  File "build/bdist.linux-x86_64/egg/kerlym/**init**.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/kerlym/agents.py", line 2, in <module>
ImportError: No module named dqn`

In fact the entire build/bdist.linux-x86_64/ folder is empty

**Comment by osh** [comment]
This is fixed it you install
Need to clean up imports for non installed running

**Comment by glazari** [comment]
Sorry, I'm not sure I understand.

I'm pretty sure I did install. wouldn't this be:
 python setup.py install

?

**Comment by osh** [comment]
this is fixed now, python setuptools wasn't installing the sub-module properly
