### ISSUE TITLE
ImportError: No module name dqn

### ISSUE THREAD

**Issue by emigmo** [osh/kerlym#6]
I have installed the Keras (1.0.3) and KeRLym(０．０．１)
But when I try to run the pg_pong.sh in the ''./kerlym/examples "'

~/git/kerlym/examples$ ./pg_pong.sh 
Using Theano backend.
Traceback (most recent call last):
  File "/usr/local/bin/kerlym", line 4, in <module>
    **import**('pkg_resources').run_script('KeRLym==0.0.1', 'kerlym')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/KeRLym-0.0.1-py2.7.egg/EGG-INFO/scripts/kerlym", line 6, in <module>

  File "build/bdist.linux-x86_64/egg/kerlym/**init**.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/kerlym/agents.py", line 2, in <module>
ImportError: No module named dqn

how I can solve this .

**Comment by osh** [comment]
please try with the latest version
