### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by eric-vader** [osh/kerlym#8]
I have installed KeRLym==0.0.2 successfully, however when i try to run any of the examples, I get:

```
$ ./run_mountaincar.sh
Using Theano backend.
dqn
<function simple_dnn at 0x7fd80cb70f50>
1e-06
[2016-08-15 11:06:52,100] Making new env: MountainCar-v0
4 [2, 2]
Traceback (most recent call last):
  File "/usr/bin/kerlym", line 4, in <module>
    __import__('pkg_resources').run_script('KeRLym==0.0.2', 'kerlym')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1512, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/KeRLym-0.0.2-py2.7.egg/EGG-INFO/scripts/kerlym", line 75, in <module>

  File "build/bdist.linux-x86_64/egg/kerlym/dqn/dqn.py", line 76, in __init__
AttributeError: 'module' object has no attribute 'set_session'
```

I am running Fedora 24 and CentOS 7. Both reached this Attribute Error when running.

```
$ pip list kerlym
cycler (0.10.0)
funcsigs (1.0.2)
gym (0.1.7)
h5py (2.6.0)
iniparse (0.4)
Keras (1.0.7)
KeRLym (0.0.2)
matplotlib (1.5.1)
mock (2.0.0)
nose (1.3.7)
numpy (1.11.1)
pbr (1.10.0)
pip (8.0.2)
protobuf (3.0.0b2)
pycurl (7.43.0)
pyglet (1.2.4)
pygobject (3.20.1)
pygpgme (0.3)
pyliblzma (0.5.3)
pyparsing (2.1.7)
python-dateutil (2.5.3)
pytz (2016.6.1)
pyxattr (0.5.3)
PyYAML (3.11)
requests (2.11.0)
rpm-python (4.13.0rc1)
scipy (0.18.0)
setuptools (25.2.0)
six (1.10.0)
tensorflow (0.10.0rc0)
Theano (0.8.2)
urlgrabber (3.10.1)
vboxapi (1.0)
wheel (0.29.0)
yum-axelget (1.0.4)
yum-metadata-parser (1.1.4)

```

Any ideas how to resolve this?

**Comment by osh** [comment]
try running with the TensorFlow backend instead of Theano backend --

**Comment by eric-vader** [comment]
[Update] Ok, it works after using TensorFlow. Is that a problem with Theano or with my installation Theano?

**Comment by Shawn617** [comment]
how to change the code to use tensorflow
